  extends: airbnb-base
  env:
    node: true
    mocha: true
    es6: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures:
      modules: true
  rules:
    indent: [error, 4]
    import/no-extraneous-dependencies: [error, {devDependencies: true}]
    import/extensions: [error, {ts: never}]
    import/no-unresolved: off # I couldn't make it work with *.ts
    no-undef: off # it doesn't work with *.ts files
    no-unused-vars: off # it doesn't work when you import classes and handled by the TSC
    object-curly-spacing: [error, never]
    comma-dangle: [error, never]
